Repository EdinburghGenomics/Reporting-App, pull requests merged in 2018-05, with the labels that each got.

#168 Refactor
  Readme.md
  bin/retrigger_aggregation.py
  bin/run_app.py
  database_versioning/v0.15_to_v0.16.py
  database_versioning/v0.16_to_v0.17.py
  etc/example_reporting.yaml
  etc/project_status_definitions.yaml
  reporting_app/__init__.py
  reporting_app/static/charts.js
  reporting_app/templates/base.html
  reporting_app/templates/charts.html
  reporting_app/templates/datatable.html
  reporting_app/templates/datatable_macro.html
  reporting_app/templates/login.html
  reporting_app/templates/proc_report.html
  reporting_app/templates/project_report.html
  reporting_app/templates/project_status.html
  reporting_app/templates/reporting_base.html
  reporting_app/templates/review_modal.html
  reporting_app/templates/run_report.html
  reporting_app/templates/sample_report.html
  reporting_app/templates/sample_status_report.html
  reporting_app/templates/tab_sets.html
  reporting_app/templates/tabbed_datatables.html
  reporting_app/templates/untabbed_datatables.html
  reporting_app/util.py
  rest_api/__init__.py
  rest_api/actions/__init__.py
  rest_api/actions/automatic_review.py
  rest_api/actions/reviews.py
  rest_api/aggregation/database_hooks.py
  rest_api/aggregation/database_side/queries.py
  rest_api/common.py
  rest_api/limsdb/__init__.py
  rest_api/limsdb/queries/__init__.py
  rest_api/limsdb/queries/data_models.py
  rest_api/limsdb/queries/factories.py
  tests/js/run_tests.html
  tests/js/test_charts.js
  tests/js/test_column_formatter.js
  tests/test_reporting_app.py
  tests/test_rest_api/__init__.py
  tests/test_rest_api/test_action/test_automatic_review.py
  tests/test_rest_api/test_aggregation/__init__.py
  tests/test_rest_api/test_aggregation/test_database_hooks.py
  tests/test_rest_api/test_limsdb.py
  tests/test_rest_api/test_limsdb/test_limsdb.py
  tests/test_rest_api/test_rest_api.py
  tests/test_rest_api/test_schema.py
Labels: in progress

#176 Test lims endpoints
  tests/test_rest_api/test_rest_api.py
Labels: NoCR

#175 Add new data release step in Finished def
  etc/project_status_definitions.yaml
Labels: NoCR, bug
